# Generated by Django 5.1.2 on 2024-11-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='first_registration',
        ),
    ]
